const defaultOptions = {
  headerShown: false,
};
const RoutesName = {
  SPLASH_STACK_SCREEN: 'SplashStack',
  AUTH_STACK_SCREEN: 'AuthStack',
  DASHBOARD_STACK_SCREEN: 'DashboardStack',
  SPLASH_SCREEN: 'SplashScreen',
  LOGIN_SCREEN: 'LoginScreen',
  SIGNUP_SCREEN: 'SignupScreen',
  ADVENTURE_SCREEN: 'Adventure',
  EXPERIENCES_SCREEN: 'ExperienceScreen',
  EXPERIENCES_STACK_SCREEN: 'ExperienceStackScreen',
  EXPERIENCES_DRAWER_SCREEN: 'ExperienceDrawerScreen',
  EXPERIENCES_DETAILS_SCREEN: 'ExperienceDetailsScreen',
  NOTIFICATION_SCREEN: 'NotifcationScreen',
  WISHLIST_SCREEN: 'WishlistScreen',
  ABOUT_US_SCREEN: 'AboutScreen',
  TERMS_SCREEN: 'TermsScreen',
  HELP_SCREEN: 'HelpScreen',
  TOUR_SCREEN: 'TourScreen',
  TOUR_DETAILS_SCREEN: 'TourDetailsScreen',
  GUIDE_SCREEN: 'GuideScreen',
  MAP_SCREEN: 'MapScreen',
  LOCATION_FOUND_SCREEN: 'LocationFoundScreen',
  LOCATION_DETAILS: 'LocationDetails',
  ROOM_BOOK: 'RoomBook',
  FEED_BACK: 'Feedback',
  PAYMENT_OPTIONS: 'PaymentScreen',
  BIKE_DETAILS: 'Bikedetails',
  EMERGENCY_CONTACT: 'EmergencyContact',
};
export {defaultOptions, RoutesName};
