export const ActionConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

  PROFILE_REQUEST: ' PROFILE_REQUEST',
  PROFILE_ERROR: 'PROFILE_ERROR',
  PROFILE_SUCCESS: 'PROFILE_SUCCESS',

  CATEGORY_REQUEST: ' CATEGORY_REQUEST',
  CATEGORY_ERROR: 'CATEGORY_ERROR',
  CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',

  LOCATION_SUCCESS: 'LOCATION_SUCCESS',
  LOCATION_ERROR: 'LOCATION_ERROR',

  RESET_STORE: 'RESET_STORE',
  GET_LOCATION: 'GET_LOCATION',
};
