export const API_URL = {
  BASE_URL: 'http://localhost:7050/api',
  BASE_URL_IMAGE: 'http://localhost:7050/',
  // BASE_URL: 'https://medicstag-back.softelevation.com',
  // BASE_URL: 'https://90ae-112-196-35-18.in.ngrok.io/api',
  lOGIN_URL: '/auth/signin',
  SIGNUP_URL: '/authSign/signup',
  CATEGORY_URL: '/category',
  EXPERIENCE_URL: '/experience',
  WISHLIST_URL: '/my-experience',
  PROFILE_URL: '/authprofile/profile',
  UNIT_URL: '/driver/unit',
  UNIT_ACTION_URL: '/driver/unit-action',
  UPDATE_PASSWORD_URL: '/driver/update-password',
  TRANSPORT_URL: '/driver/transport',
  VERIFYDOB_URL: '/driver/verify-dob',
  NOTIFICATION_URL: '/driver/notification',
  SECRET_KEY: 'admin123',
};
export const STATUS_URL = {
  Planned_Status: 'planned',
  Active_Status: 'active',
  Complete_Status: 'complete',
  Pending_Status: 'pending',
};
